### ISSUE TITLE
Angular module using gf command

### ISSUE THREAD

**Issue by abroekhuis** [kingpulsar/Grainfather-Bluetooth-Protocol#2]
Hello,

Great work, nice to have this info! Not sure if relevant for you, but just wanted to let you know that I created an angular module to control the GF via web bluetooth.

https://github.com/abroekhuis/angular-grainfather-controller

Ps: do you mind if I make a copy of the commands from your work? I'd like to have a complete repo with all relevant info.

**Comment by kingpulsar** [comment]
Cool stuff, you're free to do whatever you'd like with it, it's why I made this repo in the first place.
